name: Compile, Deploy and Run on Kubeflow
on: [push]

# Set environmental variables

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS }}
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
    steps:
    - name: Checkout files in repo
      uses: actions/checkout@v2

    - name: Auth gcloud
      run: |
        gcloud --version
        echo ${GOOGLE_APPLICATION_CREDENTIALS_JSON} > ${GOOGLE_APPLICATION_CREDENTIALS}
        echo ${GOOGLE_APPLICATION_CREDENTIALS_JSON} | gcloud auth activate-service-account ${SA_EMAIL} --project=${GCP_PROJECT} --key-file=-

    - name: Submit a pipeline
      uses: f6wbl6/kubeflow-github-action@master
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS} # required
      with:
        KUBEFLOW_URL: ${{ secrets.KUBEFLOW_URL }} # required
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        PIPELINE_FILE_PATH: "example/example_pipeline.py"
        PIPELINE_FUNCTION_NAME: "path_csv_pipeline"
        PIPELINE_PARAMETERS_PATH: "example/parameters.yaml"
        RUN_PIPELINE: True
